apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2021-09-08T16:49:33Z"
  labels:
    app.kubernetes.io/instance: go-cf-auth
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: go-cf-auth
    app.kubernetes.io/version: 1.16.0
    helm.sh/chart: go-cf-auth-0.1.0
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:labels:
          .: {}
          f:app.kubernetes.io/instance: {}
          f:app.kubernetes.io/managed-by: {}
          f:app.kubernetes.io/name: {}
          f:app.kubernetes.io/version: {}
          f:helm.sh/chart: {}
      f:spec:
        f:ports:
          .: {}
          k:{"port":80,"protocol":"TCP"}:
            .: {}
            f:port: {}
            f:protocol: {}
            f:targetPort: {}
        f:selector:
          .: {}
          f:app.kubernetes.io/instance: {}
          f:app.kubernetes.io/name: {}
        f:sessionAffinity: {}
        f:type: {}
    manager: kubectl-expose
    operation: Update
    time: "2021-09-08T16:49:33Z"
  name: go-cf-auth
  namespace: cctv
  resourceVersion: "12221154"
  uid: 2a3c0138-1163-4b3f-b445-8fa19f550de6
spec:
  clusterIP: 10.43.10.18
  clusterIPs:
  - 10.43.10.18
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app.kubernetes.io/instance: go-cf-auth
    app.kubernetes.io/name: go-cf-auth
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
