apiVersion: v1
kind: Secret
metadata:
  name: {{ include "go-cf-auth.fullname" . }}
type: Opaque
data:
  teamdomain: {{ default "NOTSET" .Values.teamurl | b64enc | quote }}
  policyaud: {{ default "NOTSET" .Values.policyaud | b64enc | quote }}
